### ISSUE TITLE
upload folder settings ignored on docker

### ISSUE THREAD

**Issue by Schnuecks** [ryanfox1985/OctoPrint-Youtube-Timelapse#23]
Hello, i setup octoprint via docker. the path for my timelapse is /octoprint/octoprint/timelapse not /home/pi/.octoprint/timelapse

My config is this

```
    youtube_timelapse:
        cert_authorized: true
        cert_saved: true
        tags: op,test,blah
        videos_folder: /octoprint/octoprint/timelapse
```

this is the error log
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.octoprint/timelapse'
2021-03-24 09:25:56,033 - tornado.access - ERROR - 500 POST /api/plugin/youtube_timelapse (192.168.195.20) 27.45ms
```

if i set the path via 
/octoprint/plugins/lib/python3.8/site-packages/octoprint_youtube_timelapse/static/js/settings.js it works

**Comment by ryanfox1985** [comment]
Hello, can you give more information about how are you using Octoprint with docker? link?

**Comment by Schnuecks** [comment]
Sure

here my docker-compose

```
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    ports:
    - 30014:80
    - 30015:8080
    devices:
    - /dev/video0:/dev/video0
    - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
    - ./volumes/octoprint:/octoprint
    environment:
    - ENABLE_MJPG_STREAMER=true
    - MJPG_STREAMER_INPUT=-r 1920x1080 -f 30
    - TZ=Europe/Berlin
```

based on this https://github.com/OctoPrint/octoprint-docker/blob/master/docker-compose.yml


the files are all there, the logs the timelapse the profile etc..
